CREATE  TABLE IF NOT EXISTS `azure-report` (
  `SubscriptionGuid` VARCHAR(255),
  `ResourceGroup` VARCHAR(255),
  `ResourceLocation` VARCHAR(255),
  `UsageDateTime` DATE,
  `MeterCategory` VARCHAR(255),
  `MeterSubcategory` VARCHAR(255),
  `MeterId` VARCHAR(255),
  `MeterName` VARCHAR(255),
  `MeterRegion` VARCHAR(255),
  `UsageQuantity` FLOAT,
  `ResourceRate` FLOAT,
  `PreTaxCost` FLOAT,
  `ConsumedService` VARCHAR(255),
  `ResourceType` VARCHAR(255),
  `InstanceId` VARCHAR(255),
  `Tags` VARCHAR(255),
  `OfferId` VARCHAR(255),
  `AdditionalInfo` VARCHAR(255),
  `ServiceInfo1` VARCHAR(255),
  `ServiceInfo2` VARCHAR(255),
  `ServiceName` VARCHAR(255),
  `ServiceTier` VARCHAR(255),
  `Currency` VARCHAR(10)
);
